--4- Trigger
CREATE OR REPLACE TRIGGER T_ACTUALIZA_NOTA_FINAL
BEFORE INSERT OR UPDATE ON UFS
FOR EACH ROW
BEGIN
    -- Calcular la nota media actualizada de la UF modificada
    :NEW.NOTA_MEDIA_UF := F_NOTA_MEDIA_UF(:NEW.CONV_EXAM, :NEW.NUM_PACS_ENT, :NEW.MIN_PACS_ENT, :NEW.NOTA_MEDIA_PACS, :NEW.NOTA_EXAM);

    -- Calcular la NOTA_FINAL_UF según la convocatoria nueva
    IF :NEW.CONV_EXAM = 'EXTRAORDINARIA' THEN
        IF :NEW.NOTA_MEDIA_UF >= 4.5 AND :NEW.NOTA_MEDIA_UF < 4.75 THEN
            :NEW.NOTA_FINAL_UF := TRUNC(:NEW.NOTA_MEDIA_UF);
        ELSE
            :NEW.NOTA_FINAL_UF := ROUND(:NEW.NOTA_MEDIA_UF);
        END IF;
    ELSIF :NEW.CONV_EXAM = 'ORDINARIA' THEN
        IF :NEW.NOTA_MEDIA_UF >= 4.5 AND :NEW.NOTA_MEDIA_UF < 4.75 THEN
            :NEW.NOTA_FINAL_UF := TRUNC(:NEW.NOTA_MEDIA_UF);
        ELSIF :NEW.NOTA_MEDIA_UF >= 4.75 AND :NEW.NOTA_MEDIA_UF < 4.9 AND :NEW.NOTA_MEDIA_PACS < 7 THEN
            :NEW.NOTA_FINAL_UF := TRUNC(:NEW.NOTA_MEDIA_UF);
        ELSIF :NEW.NOTA_MEDIA_UF >= 4.75 AND :NEW.NOTA_MEDIA_UF < 4.9 AND :NEW.NOTA_MEDIA_PACS >= 7 THEN
            :NEW.NOTA_FINAL_UF := ROUND(:NEW.NOTA_MEDIA_UF);
        ELSIF :NEW.NOTA_MEDIA_UF >= 4.9 THEN
            :NEW.NOTA_FINAL_UF := ROUND(:NEW.NOTA_MEDIA_UF);
        END IF;
    ELSIF :NEW.CONV_EXAM = 'PROYECTO' THEN
        IF :NEW.NOTA_MEDIA_UF >= 4.5 AND :NEW.NOTA_MEDIA_UF < 5 THEN
            :NEW.NOTA_FINAL_UF := TRUNC(:NEW.NOTA_MEDIA_UF);
        ELSE
            :NEW.NOTA_FINAL_UF := ROUND(:NEW.NOTA_MEDIA_UF);
        END IF;
    END IF;

    -- Actualizar el campo APRO_SUSP
    IF :NEW.NOTA_FINAL_UF IS NULL THEN
        :NEW.STAT_UF := 'PENDIENTE';
    ELSIF :NEW.NOTA_FINAL_UF < 5 THEN
        :NEW.STAT_UF := 'SUSPENSO';
    ELSE
        :NEW.STAT_UF := 'APROBADO';
    END IF;
END;
/


UPDATE UFS
SET NOTA_EXAM = 7.0
WHERE COD_ASIG = 'M02B' AND COD_UF = 'UF3';

SELECT * FROM UFS;
